# Generated by Django 4.1.2 on 2022-10-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_app', '0003_taskdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical', models.TextField(default='{}')),
            ],
        ),
    ]
